
pub const SQL_CREATE_IMAGE_IPTC: &str = r#"

CREATE TABLE image_iptc (
    image_path TEXT PRIMARY KEY,
    model_version TEXT,
    date_sent TEXT,
    time_sent TEXT,
    coded_character_set TEXT,
    record_version TEXT,
    object_type_reference TEXT,
    object_attribute_reference TEXT,
    object_name TEXT,
    edit_status TEXT,
    editorial_update TEXT,
    urgency TEXT,
    subject_reference TEXT,
    category TEXT,
    supplemental_categories TEXT,
    fixture_id TEXT,
    keywords TEXT,
    content_location_code TEXT,
    content_location_name TEXT,
    release_date TEXT,
    release_time TEXT,
    expiration_date TEXT,
    expiration_time TEXT,
    special_instructions TEXT,
    action_advised TEXT,
    reference_service TEXT,
    reference_date TEXT,
    reference_number TEXT,
    date_created TEXT,
    time_created TEXT,
    digital_date_created TEXT,
    digital_time_created TEXT,
    originating_program TEXT,
    program_version TEXT,
    object_cycle TEXT,
    by_line TEXT,
    by_line_title TEXT,
    city TEXT,
    sub_location TEXT,
    province_or_state TEXT,
    country_or_primary_location_code TEXT,
    country_or_primary_location_name TEXT,
    original_transmission_reference TEXT,
    headline TEXT,
    credit TEXT,
    source TEXT,
    copyright_notice TEXT,
    contact TEXT,
    caption TEXT,
    local_caption TEXT,
    caption_writer TEXT,
    rasterized_caption TEXT,
    image_type TEXT,
    image_orientation TEXT,
    language_identifier TEXT,
    audio_type TEXT,
    audio_sampling_rate TEXT,
    audio_sampling_resolution TEXT,
    audio_duration TEXT,
    audio_outcue TEXT,
    job_id TEXT,
    master_document_id TEXT,
    short_document_id TEXT,
    unique_document_id TEXT,
    owner_id TEXT
);
-- Optional indexes for frequently queried fields
CREATE INDEX idx_iptc_keywords ON image_iptc(keywords);
CREATE INDEX idx_iptc_by_line ON image_iptc(by_line);
CREATE INDEX idx_iptc_category ON image_iptc(category);
CREATE INDEX idx_iptc_date_created ON image_iptc(date_created);

"#;