pub mod update_aspect_ratio_indicator;
pub mod update_brightness_indicator;
pub mod update_exif_indicator;
pub mod update_similarity_indicator;
pub mod update_thumbnail_indicator;
pub mod update_ocr_text_indicator;
pub mod update_tags_indicator;
pub mod update_iptc_indicator;
pub mod update_image_paths_indicator;